[package]
name = "hangman"
version = "1.0.0"
authors = ["Arc676/Alessandro Vinciguerra <alesvinciguerra@gmail.com"]
edition = "2018"
build = "src/build.rs"

[dependencies]
qmetaobject = "0.1.4"
cstr = "0.1.0"
cpp = "0.4"
Rustic_Hangman = "0.1.0"

[build-dependencies]
cpp_build = "0.4"
